name: deploy resources

env:
  TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  # GITHUB_TOKEN: ${{ secrets.GH_PAT }}
on:
  workflow_dispatch:

  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      vm_host: ${{ steps.export_outputs.outputs.vm_host }}
      vm_user: ${{ steps.export_outputs.outputs.vm_user }}

    defaults:
      run:
        working-directory: ./infrastructure/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH Public Key
        env:
          SSH_KEY: ${{ secrets.PUBLIC_KEY }}
        run: |
          if [ -z "$SSH_KEY" ]; then
            echo "ERROR: The 'SSH_PUBLIC_KEY' secret is missing or empty!"
            exit 1
          fi

          echo "PUBLIC_KEY secret found."
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.3

      - name: Verify Terraform
        run: terraform version

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure Login
        run: |
          az account show --output table

      - name: Verify Azure CLI
        run: |
          az --version

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run:  terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan

      - name: Export Outputs for Next Jobs
        id: export_outputs
        run: |
          echo "vm_host=$(terraform output -raw vm_public_ip)" >> $GITHUB_OUTPUT
          echo "vm_user=$(terraform output -raw vm_admin_username)" >> $GITHUB_OUTPUT
  

  ansible:
    needs: terraform
    runs-on: ubuntu-latest   
    defaults:
      run:
        working-directory: ./infrastructure/ansible

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          python3 -m pip install --upgrade pip

      - name: Install latest Ansible
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible

      - name: Configure SSH
        env:
          VM_SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh

          printf '%s\n' "$VM_SSH_PRIVATE_KEY" > ~/.ssh/ansible_key

          chmod 600 ~/.ssh/ansible_key
      - name: create .env
        working-directory: ${{ github.workspace }}
        run: |
            cat <<EOF > .env
            PORT=${{ vars.PORT }}
            DIALECT=${{ secrets.DIALECT }}
            DATABASE=${{ secrets.DATABASE }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            HOST=${{ secrets.HOST }}
            DB_PORT=${{ secrets.DB_PORT}}
            TOKEN_KEY=${{ secrets.TOKEN_KEY}}
            EOF

      - name: Create Ansible inventory
        env:
          VM_HOST: ${{ needs.terraform.outputs.vm_host }}
          VM_USERNAME: ${{ needs.terraform.outputs.vm_user }}
        run: |
          cat > inventory.ini <<EOF
          [webserver]
          target ansible_host=${VM_HOST} ansible_user=${VM_USERNAME} ansible_ssh_private_key_file=~/.ssh/ansible_key
          EOF

          echo "Target Host Length: ${#VM_HOST}"
          echo "Target Username Length: ${#VM_USERNAME}"

      - name: Test SSH connection
        # working-directory: infrastructure/ansible
        run: |
          for i in {1..30}; do
            if ansible webserver -m ping; then
              echo "Server is ready."
              exit 0
            fi

            echo "Server is not ready yet. Attempt $i/30..."
            sleep 10
          done

          echo "Server did not become ready."
          exit 1

      - name: Run Ansible playbook
        # working-directory: infrastructure/ansible
        run: |
          ansible-playbook playbook.yml

      - name: Remove temporary files
        if: always()
        run: |
          rm -f ~/.ssh/ansible_key
          rm -f infrastructure/ansible/inventory.ini
          rm -f .env
